repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install