# Generated by Django 5.1.2 on 2024-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="bought_at",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
