# Generated by Django 5.1.3 on 2024-11-09 18:13

from django.db import migrations, models


def set_short_name(apps, schema_editor):
    Exchange = apps.get_model("trading", "Exchange")
    for exchange in Exchange.objects.all():
        exchange.short_name = exchange.name[:3].upper()
        exchange.save()


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_alter_account_balance_alter_account_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="short_name",
            field=models.CharField(default="NaN", max_length=3),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_short_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
