# Generated by Django 5.1.3 on 2024-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_exchange_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="name",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="short_name",
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="security",
            name="symbol",
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name="security",
            index=models.Index(
                fields=["symbol", "exchange"], name="trading_sec_symbol_0267c0_idx"
            ),
        ),
    ]
