# Generated by Django 5.1.3 on 2024-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0007_historicalsecurity"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsecurity",
            name="users_purchased",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="security",
            name="users_purchased",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
