# Generated by Django 5.1.3 on 2024-12-09 10:37

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0009_externalmarketorder_externalmarketholding_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallimitorder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicallimitorder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalmarketorder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmarketorder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalstoporder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalstoporder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="limitorder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stoporder",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stoporder",
            name="executed_price",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
