# Generated by Django 5.1.3 on 2024-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0010_alter_historicallimitorder_executed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalmarketorder",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
