# Generated by Django 5.1.3 on 2025-01-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_externalmarketorder_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsecurity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
