# Generated by Django 5.1.3 on 2024-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_statement_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bank_statements/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="identity_card_image",
            field=models.ImageField(blank=True, null=True, upload_to="identity_cards/"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
