apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deploy
  labels:
    app: celery
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/tedyst/fii-aset:{{ tag }}
          name: celery
          envFrom:
            - secretRef:
                name: django-secret
            - configMapRef:
                name: django-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: default.django.postgresql-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: default.django.postgresql-cluster.credentials.postgresql.acid.zalan.do
                  key: username
                  namespace: databases
            - name: DB_HOST
              value: postgresql-cluster.databases.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: django
            - name: RABBITMQ_URL
              value: rabbitmq-cluster.databases.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: django-rabbitmq-user-user-credentials
                  key: username
                  namespace: default
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-rabbitmq-user-user-credentials
                  key: password
                  namespace: default
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
                  namespace: default
            - name: REDIS_HOST
              value: redis-replication.databases.svc.cluster.local
            - name: RABBITMQ_VHOST
              value: django
          imagePullPolicy: Always
          command:
            - /app/backend/celery.sh
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
