apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  ttlSecondsAfterFinished: 100
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/tedyst/fii-aset:{{ tag }}
          name: django
          imagePullPolicy: Always
          command:
            - python
            - manage.py
            - migrate
          envFrom:
            - secretRef:
                name: django-secret
            - configMapRef:
                name: django-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: default.django.postgresql-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: default.django.postgresql-cluster.credentials.postgresql.acid.zalan.do
                  key: username
                  namespace: databases
            - name: DB_HOST
              value: postgresql-cluster.databases.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: django
            - name: PROMETHEUS_MULTIPROC_DIR
              value: /tmp/prometheus
            - name: ENVIRONMENT
              value: production
            - name: RABBITMQ_URL
              value: rabbitmq-cluster.databases.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: django-rabbitmq-user-user-credentials
                  key: username
                  namespace: default
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-rabbitmq-user-user-credentials
                  key: password
                  namespace: default
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
                  namespace: default
            - name: REDIS_HOST
              value: redis-replication.databases.svc.cluster.local
            - name: RABBITMQ_VHOST
              value: django
      restartPolicy: Never
