apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-deploy
  labels:
    app: nginx-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/tedyst/fii-aset:{{ tag }}-nginx
          name: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
