apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    admin:
      - superuser
      - createdb
    default.django: []
  databases:
    django: default.django
  postgresql:
    version: "16"
