apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter
data:
  key: value
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    admin:
      - superuser
      - createdb
    default.django: []
  databases:
    django: default.django
  postgresql:
    version: "16"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  sidecars:
    - name: "exporter"
      image: "quay.io/prometheuscommunity/postgres-exporter"
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          memory: 15Mi
        requests:
          cpu: 10m
          memory: 15Mi
      env:
        - name: DATA_SOURCE_URI
          value: "localhost:5432?sslmode=disable"
        - name: DATA_SOURCE_USER
          value: "postgres"
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.postgresql-cluster.credentials.postgresql.acid.zalan.do
              key: password
