apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  annotations:
    rabbitmq.com/topology-allowed-namespaces: default,databases
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  persistence:
    storage: 1Gi
  rabbitmq:
    additionalConfig: |
      disk_free_limit.absolute = 10M
      prometheus.return_per_object_metrics = true
      log.console = true
  terminationGracePeriodSeconds: 30
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - command:
                  - bash
                  - '-c'
                  - >
                    ulimit -n 65536

                    exec /opt/bitnami/scripts/rabbitmq/entrypoint.sh rabbitmq-server

                name: rabbitmq
                resources: {}
            initContainers:
              - name: setup-container
                resources:
                  requests:
                    cpu: 10m
                  limits: {}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: django-rabbitmq-user
  namespace: default
spec:
  tags:
    - policymaker
  rabbitmqClusterReference:
    name: rabbitmq-cluster
    namespace: databases
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: django-rabbitmq-vhost
  namespace: default
spec:
  name: django
  rabbitmqClusterReference:
    name: rabbitmq-cluster
    namespace: databases
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: django-rabbitmq-user-1-permission
  namespace: default
spec:
  vhost: "django"
  userReference:
    name: "django-rabbitmq-user"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-cluster
    namespace: databases
