name: Deploy
on:
  push:
    branches:
      - master
      - install-app-kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/main.yml
          directory: infrastructure/ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: collections/requirements.yml
          options: |-
            --inventory inventory.yml
